### ISSUE TITLE
X2100 directory doesn't contain bios_hap_{0,1}.bin

### ISSUE THREAD

**Issue by knothole** [xy-tech/X2100-BIOS-EC#1]
Serval files, which are mentioned in README, don't exist in x2100 directory.

- bios_hap_0.bin
- bios_hap_1.bin

Whereas these files exist but not mentioned:

- coreboot.rom
- ec_unpatched.bin

**Comment by xy-tech** [comment]
Yea I’m actively working on this at the moment. Writing a better script and updating all the files. Check back in a few days’ time?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: knothole ***@***.***>
Sent: Sunday, December 19, 2021 10:32:06 AM
To: xy-tech/X2100-BIOS-EC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xy-tech/X2100-BIOS-EC] X2100 directory doesn't contain bios_hap_{0,1}.bin (Issue #1)


Serval files, which are mentioned in README, don't exist in x2100 directory.

  *   bios_hap_0.bin
  *   bios_hap_1.bin

Whereas these files exist but not mentioned:

  *   coreboot.rom
  *   ec_unpatched.bin

**Comment by knothole** [comment]
Great. Now it has these files!

Thanks.
